---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: reset-pwd
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - delete
  - get
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: reset-pwd
  namespace: default
subjects:
- kind: ServiceAccount
  name: reset-root-account-pwd
  namespace: default
roleRef:
  kind: Role
  name: reset-pwd
  apiGroup: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reset-root-account-pwd
  namespace: default
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: delete-root-account-secret
  namespace: default
spec:
  schedule: "*/59 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: reset-root-account-pwd
          containers:
          - name: kubectl
            image: garland/kubectl:1.10.4
            command:
            - /bin/sh
            - -c
            - kubectl delete secret random -n default
          restartPolicy: OnFailure