# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  operator_build:
    machine: true 
    steps:
      - checkout
      - run:
          name: Build Operator
          command: |
                TAG=1.0.$CIRCLE_BUILD_NUM
                docker build -t $community_reg/community/operator:$TAG -f Dockerfile .
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
                TAG=1.0.$CIRCLE_BUILD_NUM
                echo $iamapikey | docker login -u iamapikey $community_reg --password-stdin
                docker push $community_reg/community/operator:$TAG
            fi 
              
workflows:
    version: 2
    all:
      jobs:
#        - build
#        - ent_op_img
         - operator_build  
