apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  labels:
    controller-tools.k8s.io: "1.0"
  name: platforms.infinimesh.infinimesh.io
spec:
  group: infinimesh.infinimesh.io
  names:
    kind: Platform
    plural: platforms
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            apiserver:
              properties:
                grpc:
                  properties:
                    host:
                      type: string
                    tls:
                      items:
                        type: object
                      type: array
                  type: object
                restful:
                  properties:
                    host:
                      type: string
                    tls:
                      items:
                        type: object
                      type: array
                  type: object
              type: object
            app:
              properties:
                host:
                  type: string
                tls:
                  items:
                    type: object
                  type: array
              type: object
            kafka:
              properties:
                bootstrapServers:
                  type: string
              type: object
            mqtt:
              properties:
                secretName:
                  type: string
              type: object
            storage:
              properties:
                storageClassName:
                  type: string
              type: object
          type: object
        status:
          type: object
  version: v1beta1
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
