apiVersion: infinimesh.infinimesh.io/v1beta1
kind: Platform
metadata:
  labels:
    controller-tools.k8s.io: "1.0"
  name: my-infinimesh
spec:
  kafka:
    bootstrapServers: "infinimesh-saas-kafka-bootstrap.kafka.svc.cluster.local:9092"
